version: '3.6'

networks:
  app-tier:
    driver: bridge

services: 
  #mysql
  db:
    container_name: mysql_container
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=chatbar_workspace
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - app-tier

  # redis
  cache:
    container_name: redis
    image: redis:alpine
    restart: always
    ports: 
      - "6379:6379"
    volumes:
      - redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - app-tier

  # application
  app:
    container_name: chatbar
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    links: 
      - db
      - cache
    restart: always
    depends_on: [db, cache]
    networks:
      - app-tier

volumes:
  mysql:
  redis:
