INSERT INTO Areas (name, created_at, updated_at)
VALUES 
    ('臺灣北部', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('臺灣中部', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('臺灣南部', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('臺灣東部', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);