INSERT INTO Genders (name, created_at, updated_at)
VALUES 
    ('男性', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('女性', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('其他', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);