INSERT INTO Interests (name, created_at, updated_at)
VALUES 
    ('健身', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('電影', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('搖滾樂', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);